enableScripts: true
enableStrictSsl: true
nodeLinker: node-modules

# This is the key setting - ignore optional build failures
optionalDependencies:
  "bigint-buffer": true
  "secp256k1": true
  "bufferutil": true
  "utf-8-validate": true